### ISSUE TITLE
Error in HBase shell non-interactive mode on version 2.4.13

### ISSUE THREAD

**Issue by lecranek** [fleeksoft/hbase#1]
Hi there, we are currently using your image [hbase-base:2.4.13.2](https://github.com/fleeksoft/hbase/pkgs/container/hbase%2Fhbase-base/29196617?tag=2.4.13.2) to deploy HBase as a component of our application. However, an error would be thrown out when we're trying to run some hbase shell commands that needs y/n verification via the non-interactive mode. Below is an example (could also refer to ticket https://issues.apache.org/jira/browse/HBASE-27116):

```bash
bash-4.4# echo -e "disable_all 'table.*'\ny" | hbase shell -n
hbase:001:0> disable_all 'table.*'
table_01
table_02

Disable the above 26 tables (y/n)?
Took 0.5008 seconds
NoMethodError: undefined method `chomp' for nil:NilClass
                     command at uri:classloader:/shell/commands/disable_all.rb:41
                command_safe at uri:classloader:/shell/commands.rb:49
  translate_hbase_exceptions at uri:classloader:/shell/commands.rb:122
                command_safe at uri:classloader:/shell/commands.rb:49
            internal_command at uri:classloader:/shell.rb:211
                     command at uri:classloader:/shell.rb:203
                 disable_all at uri:classloader:/shell.rb:166
                    evaluate at (hbase):1
                        eval at org/jruby/RubyKernel.java:1048
                    evaluate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/workspace.rb:85
                    evaluate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/context.rb:380
                  eval_input at uri:classloader:/irb/hirb.rb:115
               signal_status at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:623
                  eval_input at uri:classloader:/irb/hirb.rb:112
    each_top_level_statement at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/ruby-lex.rb:246
                        loop at org/jruby/RubyKernel.java:1442
    each_top_level_statement at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/ruby-lex.rb:232
                       catch at org/jruby/RubyKernel.java:1189
    each_top_level_statement at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/ruby-lex.rb:231
                  eval_input at uri:classloader:/irb/hirb.rb:111
                         run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:428
                       catch at org/jruby/RubyKernel.java:1189
                         run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:427
                      <main> at classpath:/jar-bootstrap.rb:223
```
I am wondering if you guys are planning to make an upgraded image like 2.4.14 or higher in future. And thanks for you image and chart, it helps a lot.

**Comment by itboy87** [comment]
Hi @lecranek, Today I pushed a new version: ghcr.io/fleeksoft/hbase/hbase-master:2.4.14

Please give it try Hadoop also upgraded to 3.3.4

**Comment by itboy87** [comment]
Hi @lecranek , Today I pushed a new version: ghcr.io/fleeksoft/hbase/hbase-base:2.4.14
Please give it a try.
Hadoop also upgraded to 3.3.4

**Comment by lecranek** [comment]
@itboy87 Thanks for your update. However, it seems that HBase officially does not fix this issue yet in 2.4.14. We might just wait for another stable release now.
```bash
bash-4.4# echo -e "version" | hbase shell -n
hbase:001:0> version
2.4.14, r2e7d75a892000071a7479b2f668c4db7a241be3f, Tue Aug 23 23:33:09 UTC 2022
Took 0.0017 seconds
hbase:002:0>
bash-4.4# echo -e "disable_all 'table.*'\ny" | hbase shell -n
hbase:001:0> disable_all 'table.*'
table_1
table_2

Disable the above 2 tables (y/n)?
Took 0.5590 seconds
NoMethodError: undefined method `chomp' for nil:NilClass
                     command at uri:classloader:/shell/commands/disable_all.rb:41
                command_safe at uri:classloader:/shell/commands.rb:49
  translate_hbase_exceptions at uri:classloader:/shell/commands.rb:122
                command_safe at uri:classloader:/shell/commands.rb:49
            internal_command at uri:classloader:/shell.rb:211
                     command at uri:classloader:/shell.rb:203
                 disable_all at uri:classloader:/shell.rb:166
                    evaluate at (hbase):1
                        eval at org/jruby/RubyKernel.java:1048
                    evaluate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/workspace.rb:85
                    evaluate at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/context.rb:380
                  eval_input at uri:classloader:/irb/hirb.rb:115
               signal_status at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:623
                  eval_input at uri:classloader:/irb/hirb.rb:112
    each_top_level_statement at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/ruby-lex.rb:246
                        loop at org/jruby/RubyKernel.java:1442
    each_top_level_statement at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/ruby-lex.rb:232
                       catch at org/jruby/RubyKernel.java:1189
    each_top_level_statement at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/ruby-lex.rb:231
                  eval_input at uri:classloader:/irb/hirb.rb:111
                         run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:428
                       catch at org/jruby/RubyKernel.java:1189
                         run at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:427
                      <main> at classpath:/jar-bootstrap.rb:223
bash-4.4#

```
